global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
  - job_name: 'express_app'
    static_configs:
      - targets: ['app:3001']
      
remote_write:
  - url: "http://mimir:9009/api/v1/push"
