{
 "title": "Disk Usage Stats",
 "description": "Disk usage stats for lotus host machines",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Legend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host IP Legend",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(kube_pod_info{namespace=~\"default|network\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Class Legend",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(kube_persistentvolumeclaim_info{namespace=~\"default|network|monitoring\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk stats for /nvme/disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Used space on /nvme/disk (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max without(node) (\n  topk(20, (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/nvme/disk\"} - node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/nvme/disk\"}))  /\n  topk(20, (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/nvme/disk\"}))\n* 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available space on /nvme/disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max without(node) (topk(20, node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/nvme/disk\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk stats for /mnt/raid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Used space on /mnt/raid (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max without(node) (\n  topk(20, (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/mnt/raid\"} - node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/mnt/raid\"}))  /\n  topk(20, (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/mnt/raid\"}))\n* 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available space on /mnt/raid (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max without(node) (topk(20, node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/mnt/raid\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk stats for PVs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used space on PVs (%)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max without(instance,node,endpoint,job,metrics_path,namespace,service)(\n  topk(20, kubelet_volume_stats_used_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}) /\n  topk(20, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})\n* 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available space on PVs (%)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max without(instance,node,endpoint,job,metrics_path,namespace,service)(\n  topk(20, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Disk stats for /", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Used space on / (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max without(node) (\n  topk(20, (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"}))  /\n  topk(20, (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"}))\n* 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available space on / (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max without(node) (topk(20, node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}