services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning 
    depends_on:
      - prometheus
  
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertm/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  papercut:
   image: jijiechen/papercut:latest
   ports:
     - "25:25"
     - "37408:37408"
   environment:
     - TZ=UTC

  alloy:
    image: grafana/alloy:latest
    working_dir: /disco
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  loki:
    image: grafana/loki:2.9.10
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.10
    command: -config.file=/etc/promtail/config.yml

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    working_dir: /disco
    volumes:
      - C:\Sandbox\Discovery\discoverybank.services.client:/disco
    ports:
      - "9100:9100"
      
  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir/config.yaml"]
    volumes:
      - ./mimir/mimir-config.yml:/etc/mimir/config.yaml
    ports:
      - "9009:9009"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
  
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
      