global:
  smtp_smarthost: 'papercut:25'
  smtp_from: 'alerts@example.com'
  smtp_require_tls: false

receivers:
  - name: 'email'
    email_configs:
      - to: 'your-email@example.com'
        send_resolved: true

route:
  receiver: 'email'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h